import {
  event1,
  event2,
  event3,
  event4,
  heroImage,
  heroImage1,
  heroImage2,
  heroImage3,
  image1,
  image2,
  image3,
  image4,
  image5,
  image6,
  image7,
  image8,
  image9,
  image10,
  test1,
  test2,
  test3,
  test4,
  test5,
  test6,
} from './imagesData/imags'

export const swiperHero = [
  {
    id: 1,
    image: heroImage,
    title: 'Anniversary Cake 1',
    category: 'Chocolate',
    price: ' 300.00',
  },
  {
    id: 2,
    image: heroImage1,
    title: 'Anniversary Cake 2',
    category: 'Chocolate',
    price: ' 300.00',
  },
  {
    id: 3,
    image: heroImage2,
    title: 'Anniversary Cake 3',
    category: 'Chocolate',
    price: ' 300.00',
  },
  {
    id: 4,
    image: heroImage3,
    title: 'Anniversary Cake 4',
    category: 'Chocolate',
    price: ' 300.00',
  },
  {
    id: 5,
    image: heroImage2,
    title: 'Anniversary Cake 5',
    category: 'Chocolate',
    price: ' 300.00',
  },
  {
    id: 6,
    image: heroImage,
    title: 'Anniversary Cake 6',
    category: 'Chocolate',
    price: ' 300.00',
  },
]

export const storyData = [
  {
    id: 1,
    image: image1,
    title: 'Custom Cake 1',
    category: 'Custom Cake',
    startPrice: '300.00',
    endPrice: '500',
    sku: '1',
  },
  {
    id: 2,
    image: image2,
    title: 'Custom Cake 2',
    category: 'Custom Cake',
    startPrice: ' 350.00',
    endPrice: '500',
    sku: '2',
  },
  {
    id: 3,
    image: image3,
    title: 'Custom Cake 3',
    category: 'Custom Cake',
    startPrice: ' 400.00',
    endPrice: '500',
    sku: '3',
  },
  {
    id: 18,
    image: image4,
    title: 'Custom Cake 4',
    category: 'Custom Cake',
    startPrice: ' 400.00',
    endPrice: '500',
    sku: '4',
  },
  {
    id: 21,
    image: image1,
    title: 'Custom Cake 1',
    category: 'Custom Cake',
    startPrice: '300.00',
    endPrice: '500',
    sku: '1',
  },
  {
    id: 22,
    image: image2,
    title: 'Custom Cake 2',
    category: 'Custom Cake',
    startPrice: ' 350.00',
    endPrice: '500',
    sku: '2',
  },
  {
    id: 23,
    image: image3,
    title: 'Custom Cake 3',
    category: 'Custom Cake',
    startPrice: ' 400.00',
    endPrice: '500',
    sku: '3',
  },
  {
    id: 218,
    image: image4,
    title: 'Custom Cake 4',
    category: 'Custom Cake',
    startPrice: ' 400.00',
    endPrice: '500',
    sku: '4',
  },
  {
    id: 17,
    image: image6,
    title: 'Custom Cake 4',
    category: 'Custom Cake',
    startPrice: ' 400.00',
    endPrice: '500',
    sku: '5',
  },
  {
    id: 4,
    image: image5,
    title: 'Brownie',
    category: 'Brownie',
    startPrice: ' 350.00',
    endPrice: '500',
    sku: '6',
  },
  {
    id: 5,
    image: image6,
    title: 'Brownie 1',
    category: 'Chocolate',
    startPrice: ' 350.00',
    endPrice: '500',
    sku: '7',
  },
  {
    id: 6,
    image: image3,
    title: 'Brownie 2',
    category: 'Brownie',
    startPrice: ' 360.00',
    endPrice: '500',
  },
  {
    id: 14,
    image: image5,
    title: 'Brownie 3',
    category: 'Brownie',
    startPrice: ' 360.00',
    endPrice: '500',
  },
  {
    id: 7,
    image: image2,
    title: 'Masson jar cake',
    category: 'Masson jar cake',
    startPrice: ' 350.00',
    endPrice: '500',
  },
  {
    id: 8,
    image: image5,
    title: 'Masson jar cake 1',
    category: 'Masson jar cake',
    startPrice: ' 350.00',
    endPrice: '500',
  },
  {
    id: 9,
    image: image1,
    title: 'Masson jar cake 2',
    category: 'Masson jar cake',
    startPrice: ' 360.00',
    endPrice: '500',
  },
  {
    id: 15,
    image: image6,
    title: 'Masson jar cake 5',
    category: 'Masson jar cake',
    startPrice: ' 360.00',
    endPrice: '500',
  },
  {
    id: 10,
    image: image2,
    title: 'Mini Bites',
    category: 'Mini Bites',
    startPrice: ' 350.00',
    endPrice: '500',
  },
  {
    id: 11,
    image: image4,
    title: 'Mini Bites 1',
    category: 'Mini Bites',
    startPrice: ' 350.00',
    endPrice: '500',
  },
  {
    id: 12,
    image: image1,
    title: 'Mini Bites 2',
    category: 'Mini Bites',
    startPrice: ' 360.00',
    endPrice: '500',
  },
  {
    id: 16,
    image: image3,
    title: 'Mini Bites 3',
    category: 'Mini Bites',
    startPrice: ' 360.00',
    endPrice: '500',
  },
]

export const cutomize = [
  {
    id: 1,
    title: 'Custom Artistic Designs',
    description:
      "Our cakes are not just desserts—they're edible masterpieces. We specialize in creating highly detailed",
  },
  {
    id: 2,
    title: 'Innovative Flavor Combinations',
    description:
      "Our cakes are not just desserts—they're edible masterpieces. We specialize in creating highly detailed",
  },
  {
    id: 3,
    title: 'Handcrafted Excellence',
    description:
      "Our cakes are not just desserts—they're edible masterpieces. We specialize in creating highly detailed",
  },
  {
    id: 4,
    title: 'Personalized Client Experience',
    description:
      "Our cakes are not just desserts—they're edible masterpieces. We specialize in creating highly detailed",
  },
]

export const celebrations = [
  {
    id: 1,
    image: image1,
    title: 'Lorem Ipsum is sim...',
    price: '300.00',
  },
  {
    id: 2,
    image: image2,
    title: 'Lorem Ipsum is sim...',
    price: '300.00',
  },
  {
    id: 3,
    image: image3,
    title: 'Lorem Ipsum is sim...',
    price: '300.00',
  },
  {
    id: 4,
    image: image4,
    title: 'Lorem Ipsum is sim...',
    price: '300.00',
  },
  {
    id: 5,
    image: image5,
    title: 'Lorem Ipsum is sim...',
    price: '300.00',
  },
  {
    id: 6,
    image: image6,
    title: 'Lorem Ipsum is sim...',
    price: '300.00',
  },
  {
    id: 7,
    image: image3,
    title: 'Lorem Ipsum is sim...',
    price: '300.00',
  },
  {
    id: 8,
    image: image2,
    title: 'Lorem Ipsum is sim...',
    price: '300.00',
  },
]

export const occasionsData = [
  {
    id: 1,
    image: image1,
    title: 'Birthday Cake 1',
    category: 'Birthday',
    price: '300.00',
  },
  {
    id: 2,
    image: image2,
    title: 'Birthday Cake 2',
    category: 'Birthday',
    price: ' 350.00',
  },
  {
    id: 3,
    image: image3,
    title: 'Birthday Cake 3',
    category: 'Birthday',
    price: ' 400.00',
  },
  {
    id: 18,
    image: image4,
    title: 'Birthday Cake 4',
    category: 'Birthday',
    price: ' 400.00',
  },
  {
    id: 16,
    image: image6,
    title: 'Birthday Cake 4',
    category: 'Birthday',
    price: ' 400.00',
  },
  {
    id: 4,
    image: image5,
    title: 'Anniversary cake',
    category: 'Anniversary',
    price: ' 350.00',
  },
  {
    id: 5,
    image: image2,
    title: 'Anniversary 1',
    category: 'Anniversary',
    price: ' 350.00',
  },
  {
    id: 6,
    image: image3,
    title: 'Anniversary 2',
    category: 'Anniversary',
    price: ' 360.00',
  },
  {
    id: 14,
    image: image6,
    title: 'Anniversary 3',
    category: 'Anniversary',
    price: ' 360.00',
  },
  {
    id: 7,
    image: image3,
    title: 'Wedding cake',
    category: 'Wedding',
    price: ' 350.00',
  },
  {
    id: 8,
    image: image5,
    title: 'Wedding cake 1',
    category: 'Wedding',
    price: ' 350.00',
  },
  {
    id: 9,
    image: image2,
    title: 'Wedding cake 2',
    category: 'Wedding',
    price: ' 360.00',
  },
  {
    id: 15,
    image: image1,
    title: 'Wedding cake 5',
    category: 'Wedding',
    price: ' 360.00',
  },
  {
    id: 10,
    image: image6,
    title: 'Baby Shower',
    category: 'Baby Shower',
    price: ' 350.00',
  },
  {
    id: 11,
    image: image2,
    title: 'Baby Shower 1',
    category: 'Baby Shower',
    price: ' 350.00',
  },
  {
    id: 12,
    image: image3,
    title: 'Chef’s Special 2',
    category: 'Chef’s Special',
    price: ' 360.00',
  },
  {
    id: 16,
    image: image1,
    title: 'Cup Cake 3',
    category: 'Cup Cake',
    price: ' 360.00',
  },
]

export const miniBitesData = [
  {
    id: 1,
    image: image7,
    title: 'Brownie Cake 1',
    category: 'Brownie',
    price: '300.00',
  },
  {
    id: 2,
    image: image8,
    title: 'Brownie Cake 2',
    category: 'Brownie',
    price: ' 350.00',
  },
  {
    id: 3,
    image: image9,
    title: 'Brownie Cake 3',
    category: 'Brownie',
    price: ' 400.00',
  },
  {
    id: 18,
    image: image10,
    title: 'Brownie Cake 4',
    category: 'Brownie',
    price: ' 400.00',
  },
  {
    id: 16,
    image: image8,
    title: 'Brownie Cake 4',
    category: 'Brownie',
    price: ' 400.00',
  },
  {
    id: 4,
    image: image5,
    title: 'Cake Slice ',
    category: 'Cake Slice',
    price: ' 350.00',
  },
  {
    id: 5,
    image: image2,
    title: 'Cake Slice 1',
    category: 'Cake Slice',
    price: ' 350.00',
  },
  {
    id: 6,
    image: image3,
    title: 'Cake Slice 2',
    category: 'Cake Slice',
    price: ' 360.00',
  },
  {
    id: 14,
    image: image6,
    title: 'Cake Slice 3',
    category: 'Cake Slice',
    price: ' 360.00',
  },
  {
    id: 7,
    image: image3,
    title: 'Cookie ',
    category: 'Cookie',
    price: ' 350.00',
  },
  {
    id: 8,
    image: image5,
    title: 'Cookie  1',
    category: 'Cookie',
    price: ' 350.00',
  },
  {
    id: 9,
    image: image2,
    title: 'Cookie  2',
    category: 'Cookie',
    price: ' 360.00',
  },
  {
    id: 15,
    image: image1,
    title: 'Cookie  5',
    category: 'Cookie',
    price: ' 360.00',
  },
  {
    id: 10,
    image: image6,
    title: 'Cup Cake',
    category: 'Cup Cake',
    price: ' 350.00',
  },
  {
    id: 11,
    image: image2,
    title: 'Cup Cake 1',
    category: 'Cup Cake',
    price: ' 350.00',
  },
  {
    id: 12,
    image: image3,
    title: 'Mini Cakes 2',
    category: 'Mini Cakes',
    price: ' 360.00',
  },
  {
    id: 16,
    image: image1,
    title: 'Small Dessert',
    category: 'Small Dessert',
    price: ' 360.00',
  },
]

export const testimonialsData = [
  {
    id: 1,
    imageUrl: test1,
    title: 'PRESENTATION & TASTE',
    description:
      'For many months now, I have had the delight of eating an array of Ribbons and Ballons’s cakes, services and beautiful yummy cupcakes. They are delicious, full of classic and inventive flavors. They say flavor is only part of taste. Presentation is a factor too. You get a A+ in decoration for not only  cupcakes but for cakes too. I would recommend them for anyone who  wants a professional services , amazing packing, good  cakes, on time delivery, prompt and the best for corporate events.',
  },
  {
    id: 2,
    imageUrl: test2,
    title: 'PRESENTATION & TASTE',
    description:
      'For many months now, I have had the delight of eating an array of Ribbons and Ballons’s cakes, services and beautiful yummy cupcakes. They are delicious, full of classic and inventive flavors. They say flavor is only part of taste. Presentation is a factor too. You get a A+ in decoration for not only  cupcakes but for cakes too. I would recommend them for anyone who  wants a professional services , amazing packing, good  cakes, on time delivery, prompt and the best for corporate events.',
  },
  {
    id: 3,
    imageUrl: test3,
    title: 'PRESENTATION & TASTE',
    description:
      'For many months now, I have had the delight of eating an array of Ribbons and Ballons’s cakes, services and beautiful yummy cupcakes. They are delicious, full of classic and inventive flavors. They say flavor is only part of taste. Presentation is a factor too. You get a A+ in decoration for not only  cupcakes but for cakes too. I would recommend them for anyone who  wants a professional services , amazing packing, good  cakes, on time delivery, prompt and the best for corporate events.',
  },
  {
    id: 4,
    imageUrl: test4,
    title: 'PRESENTATION & TASTE',
    description:
      'For many months now, I have had the delight of eating an array of Ribbons and Ballons’s cakes, services and beautiful yummy cupcakes. They are delicious, full of classic and inventive flavors. They say flavor is only part of taste. Presentation is a factor too. You get a A+ in decoration for not only  cupcakes but for cakes too. I would recommend them for anyone who  wants a professional services , amazing packing, good  cakes, on time delivery, prompt and the best for corporate events.',
  },
  {
    id: 5,
    imageUrl: test5,
    title: 'PRESENTATION & TASTE',
    description:
      'For many months now, I have had the delight of eating an array of Ribbons and Ballons’s cakes, services and beautiful yummy cupcakes. They are delicious, full of classic and inventive flavors. They say flavor is only part of taste. Presentation is a factor too. You get a A+ in decoration for not only  cupcakes but for cakes too. I would recommend them for anyone who  wants a professional services , amazing packing, good  cakes, on time delivery, prompt and the best for corporate events.',
  },
  {
    id: 6,
    imageUrl: test6,
    title: 'PRESENTATION & TASTE',
    description:
      'For many months now, I have had the delight of eating an array of Ribbons and Ballons’s cakes, services and beautiful yummy cupcakes. They are delicious, full of classic and inventive flavors. They say flavor is only part of taste. Presentation is a factor too. You get a A+ in decoration for not only  cupcakes but for cakes too. I would recommend them for anyone who  wants a professional services , amazing packing, good  cakes, on time delivery, prompt and the best for corporate events.',
  },
]

export const eventsData = [
  {
    id: 1,
    title: 'Personalized Gifts',
    images: [event1, event2, event3, event4],
  },
  {
    id: 2,
    title: 'Events Catering',
    images: [event2, event1, event1, event4],
  },
  {
    id: 3,
    title: 'Team Building Workshops',
    images: [event1, event2, event3, event4],
  },
  {
    id: 4,
    title: 'Weddings & Special Events',
    images: [event2, event1, event1, event4],
  },
]

export const eventsList = [
  'Elevate your next event with Ribbons & Balloons.',
  'Our expert team specializes in personalizing cakes, cupcakes, and desserts with your brand or image.',
  'Just complete the form below to get started, no event is too big or',
]
